version: '3'

services:
  rails:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "80:3000"
    links:
      - postgres
    env_file:
      - variables.env
  postgres:
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - variables.env

